[general]
email = ""

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[theme]
base = "light"
primaryColor = "#163B5C"
backgroundColor = "#F9F9FF"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#111C2D"
font = "sans serif"
