/**
 * Unified ID generation utilities
 * Uses crypto.randomUUID() when available, falls back to timestamp + random
 */

/**
 * Generate a unique ID
 * @param prefix Optional prefix for the ID (e.g., 'meeting', 'template', 'action')
 * @returns A unique ID string
 */
export function generateId(prefix?: string): string {
  let id: string;

  // Use crypto.randomUUID() if available (most modern browsers)
  if (typeof crypto !== 'undefined' && crypto.randomUUID) {
    id = crypto.randomUUID();
  } else {
    // Fallback: timestamp + random string
    const timestamp = Date.now().toString(36);
    const random = Math.random().toString(36).slice(2, 11);
    id = `${timestamp}-${random}`;
  }

  return prefix ? `${prefix}_${id}` : id;
}

/**
 * Validate if an ID looks like it was generated by Date.now() (old format)
 * These IDs are typically pure numeric timestamps like "1779274278310"
 */
export function isLegacyTimestampId(id: string): boolean {
  // Check if ID is a pure numeric string with 10-13 digits (typical Unix timestamp in ms)
  return /^\d{10,13}$/.test(id);
}

/**
 * Check if two IDs are the same (handles both string and number IDs)
 */
export function isSameId(id1: string | number, id2: string | number): boolean {
  return String(id1) === String(id2);
}
